First pod implementation
Arquisoft/lomap_en1a pull request #106
Opened 2023-04-05 16:03 UTC by RubendelRey

The rest api has been changed in order to use the pods.
All the source code has been moved to a src folder, and all the controllers, services and repositories have been adapted.
The string for the database connection is not in the code, so have in mind that anyone who wants to use the rest api has to complete it. The login must be adapted to be used by the webapp and webapp calls to the rest api should be changed in order to use properly the new endpoints defined one the rest api.

2023-04-05 16:13 UTC, alvaroglezeri commented on docs/images/ControllerDiagram.svg
Missing user controller?

2023-04-05 16:34 UTC, alvaroglezeri commented on docs/images/businessDiagram.svg
Why has this been changed?

2023-04-05 16:37 UTC, alvaroglezeri commented on domain/User.ts
Why does this no longer extend BaseEntity?

2023-04-05 16:51 UTC, RubendelRey commented on docs/images/ControllerDiagram.svg
The documentation is not yet updated, I will update in the following days.

2023-04-05 16:52 UTC, RubendelRey commented on domain/User.ts
Because users do not have an id, users entity is just to send the username of the user and its web id

2023-04-05 16:53 UTC, RubendelRey commented on docs/images/businessDiagram.svg
It was an old update from the first prototype. All documentation has to be updated (I will update it soon)

2023-04-05 17:04 UTC, alvaroglezeri commented on webapp/src/domain/Visibility.ts
Why has this been changed?

2023-04-05 17:06 UTC, alvaroglezeri requested changes
Review comments in each change. Most of them are related with the domain changes, and there are some classes which do not have comments because they are repeated elsewhere. POD stuff is beautiful 👍🏼.

2023-04-05 17:07 UTC, alvaroglezeri commented on domain/User.ts
Fancy, so similar to a DTO. Thanks!

2023-04-05 17:30 UTC, UO281801 requested changes
The domain directory outside the restApi folder causes problems when building the docker image, maybe we should move it inside the rest api

2023-04-05 23:11 UTC, UO281801 commented on restapi/src/controllers/users.ts
In the login endpoint, the provider and redirection URL are missing as parameters in the GET URL.

2023-04-05 23:13 UTC, UO281801 requested changes
Unused imports should be removed to avoid unwanted warnings.

2023-04-06 16:29 UTC, UO282497 commented
Unused imports were removed and the login works well with the parameters

2023-04-06 16:29 UTC, merged